// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCBdtWKhq42i3n14ZiC8kzzvLyaSD8Ekw',
    appId: '1:456080599434:web:f76f627e298e1c576d4073',
    messagingSenderId: '456080599434',
    projectId: 'inclass12-ed12',
    authDomain: 'inclass12-ed12.firebaseapp.com',
    storageBucket: 'inclass12-ed12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF2LalyMO7YkrUaKcK0VnnCDQJQ7cU-yI',
    appId: '1:456080599434:android:c1b373024d5fdeba6d4073',
    messagingSenderId: '456080599434',
    projectId: 'inclass12-ed12',
    storageBucket: 'inclass12-ed12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeOc-wgKYxZSDsMBuMwqKF3hPwg0stYR4',
    appId: '1:456080599434:ios:e6467a81b1fea2356d4073',
    messagingSenderId: '456080599434',
    projectId: 'inclass12-ed12',
    storageBucket: 'inclass12-ed12.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeOc-wgKYxZSDsMBuMwqKF3hPwg0stYR4',
    appId: '1:456080599434:ios:e6467a81b1fea2356d4073',
    messagingSenderId: '456080599434',
    projectId: 'inclass12-ed12',
    storageBucket: 'inclass12-ed12.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCBdtWKhq42i3n14ZiC8kzzvLyaSD8Ekw',
    appId: '1:456080599434:web:d8f4169310ca22b76d4073',
    messagingSenderId: '456080599434',
    projectId: 'inclass12-ed12',
    authDomain: 'inclass12-ed12.firebaseapp.com',
    storageBucket: 'inclass12-ed12.firebasestorage.app',
  );

}